import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { registerAdapter } from './base-adapter.js';
import type { AdapterDefinition, AdapterInput, AdapterOutput } from './base-adapter.js';

export const AiderAdapter: AdapterDefinition = {
  id: 'aider',
  displayName: 'Aider',
  description: '→ CONVENTIONS.md',

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, '.aider.conf.yml')) || existsSync(join(projectRoot, 'CONVENTIONS.md'));
  },

  generate(input: AdapterInput): AdapterOutput[] {
    const { content } = input;
    const lines: string[] = [];
    lines.push(`# ${content.projectName} Conventions`);
    lines.push('');
    lines.push('Generated by reins. Source: .reins/constraints.yaml');
    lines.push('');
    lines.push(`This is a ${content.projectSummary} project.`);
    lines.push('');
    if (content.criticalRules.length > 0) {
      lines.push('## Must Follow');
      lines.push('');
      lines.push(...content.criticalRules.map(r => `- ${r}`));
      lines.push('');
    }
    if (content.importantRules.length > 0) {
      lines.push('## Should Follow');
      lines.push('');
      lines.push(...content.importantRules.map(r => `- ${r}`));
      lines.push('');
    }
    if (content.helpfulRules.length > 0) {
      lines.push('## Consider');
      lines.push('');
      lines.push(...content.helpfulRules.map(r => `- ${r}`));
      lines.push('');
    }
    if (content.commandsBlock) {
      lines.push('## Commands');
      lines.push('');
      lines.push(content.commandsBlock);
      lines.push('');
    }

    return [{ path: 'CONVENTIONS.md', content: lines.join('\n'), label: 'Aider conventions' }];
  },
};

registerAdapter(AiderAdapter);
