import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { registerAdapter } from './base-adapter.js';
import type { AdapterDefinition, AdapterInput, AdapterOutput } from './base-adapter.js';

export const AmazonQAdapter: AdapterDefinition = {
  id: 'amazon-q',
  displayName: 'Amazon Q',
  description: '→ .amazonq/rules/reins.md',

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, '.amazonq'));
  },

  generate(input: AdapterInput): AdapterOutput[] {
    const { content } = input;
    const lines: string[] = [];
    lines.push(`# ${content.projectName} — Project Rules`);
    lines.push('');
    lines.push('Generated by reins. Source: .reins/constraints.yaml');
    lines.push('');
    lines.push(`Stack: ${content.projectSummary}`);
    lines.push('');
    const allRules = [...content.criticalRules, ...content.importantRules];
    if (allRules.length > 0) {
      lines.push('## Rules');
      lines.push('');
      lines.push(...allRules.map(r => `- ${r}`));
      lines.push('');
    }
    if (content.commandsBlock) {
      lines.push('## Commands');
      lines.push('');
      lines.push(content.commandsBlock);
      lines.push('');
    }

    return [{ path: '.amazonq/rules/reins.md', content: lines.join('\n'), label: 'Amazon Q rules' }];
  },
};

registerAdapter(AmazonQAdapter);
