import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { registerAdapter } from './base-adapter.js';
import type { AdapterDefinition, AdapterInput, AdapterOutput } from './base-adapter.js';

export const AntigravityAdapter: AdapterDefinition = {
  id: 'antigravity',
  displayName: 'Antigravity',
  description: '→ GEMINI.md + AGENTS.md',

  detect(projectRoot: string): boolean {
    // Antigravity reads both GEMINI.md and AGENTS.md; detect its workspace markers
    return existsSync(join(projectRoot, '.antigravity'))
      || existsSync(join(projectRoot, 'GEMINI.md'));
  },

  generate(input: AdapterInput): AdapterOutput[] {
    const { content } = input;
    const outputs: AdapterOutput[] = [];

    // GEMINI.md — Antigravity-specific overrides (takes priority over AGENTS.md)
    const geminiLines: string[] = [];
    geminiLines.push(`# ${content.projectName}`);
    geminiLines.push('');
    geminiLines.push('Generated by reins. Source: .reins/constraints.yaml');
    geminiLines.push('');
    geminiLines.push(`**Stack**: ${content.projectSummary}`);
    geminiLines.push('');

    if (content.commandsBlock) {
      geminiLines.push('## Commands');
      geminiLines.push('');
      geminiLines.push(content.commandsBlock);
      geminiLines.push('');
    }

    geminiLines.push('## Rules');
    geminiLines.push('');
    const allRules = [...content.criticalRules, ...content.importantRules];
    for (const rule of allRules) {
      geminiLines.push(`- ${rule}`);
    }
    geminiLines.push('');

    if (content.helpfulRules.length > 0) {
      geminiLines.push('## Guidelines');
      geminiLines.push('');
      geminiLines.push(...content.helpfulRules.map(r => `- ${r}`));
      geminiLines.push('');
    }

    outputs.push({ path: 'GEMINI.md', content: geminiLines.join('\n'), label: 'Antigravity context (GEMINI.md)' });

    // AGENTS.md — cross-tool shared rules (also read by Antigravity)
    const agentsLines: string[] = [];
    agentsLines.push(`# ${content.projectName}`);
    agentsLines.push('');
    agentsLines.push('Generated by reins. Source: .reins/constraints.yaml');
    agentsLines.push('');
    agentsLines.push(`**Stack**: ${content.projectSummary}`);
    agentsLines.push(`**Architecture**: ${content.architectureSummary}`);
    agentsLines.push('');

    if (content.commandsBlock) {
      agentsLines.push('## Commands');
      agentsLines.push('');
      agentsLines.push(content.commandsBlock);
      agentsLines.push('');
    }

    if (content.criticalRules.length > 0) {
      agentsLines.push('## Critical');
      agentsLines.push('');
      agentsLines.push(...content.criticalRules.map(r => `- ${r}`));
      agentsLines.push('');
    }
    if (content.importantRules.length > 0) {
      agentsLines.push('## Important');
      agentsLines.push('');
      agentsLines.push(...content.importantRules.map(r => `- ${r}`));
      agentsLines.push('');
    }
    if (content.helpfulRules.length > 0) {
      agentsLines.push('## Guidelines');
      agentsLines.push('');
      agentsLines.push(...content.helpfulRules.map(r => `- ${r}`));
      agentsLines.push('');
    }

    outputs.push({ path: 'AGENTS.md', content: agentsLines.join('\n'), label: 'Antigravity context (AGENTS.md)' });

    return outputs;
  },
};

registerAdapter(AntigravityAdapter);
