import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { registerAdapter } from './base-adapter.js';
import type { AdapterDefinition, AdapterInput, AdapterOutput } from './base-adapter.js';

export const AugmentAdapter: AdapterDefinition = {
  id: 'augment',
  displayName: 'Augment Code',
  description: '→ .augment-guidelines',

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, '.augment-guidelines')) || existsSync(join(projectRoot, '.augment'));
  },

  generate(input: AdapterInput): AdapterOutput[] {
    const { content } = input;
    const lines: string[] = [];
    lines.push(`# ${content.projectName} — Augment Guidelines`);
    lines.push('');
    lines.push('Generated by reins. Source: .reins/constraints.yaml');
    lines.push('');
    lines.push(`Stack: ${content.projectSummary}`);
    lines.push('');
    const allRules = [...content.criticalRules, ...content.importantRules, ...content.helpfulRules];
    for (const rule of allRules) {
      lines.push(`- ${rule}`);
    }
    lines.push('');

    return [{ path: '.augment-guidelines', content: lines.join('\n'), label: 'Augment Code guidelines' }];
  },
};

registerAdapter(AugmentAdapter);
