import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { registerAdapter } from './base-adapter.js';
import type { AdapterDefinition, AdapterInput, AdapterOutput } from './base-adapter.js';

export const ClineAdapter: AdapterDefinition = {
  id: 'cline',
  displayName: 'Cline / Roo Code',
  description: '→ .clinerules',

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, '.clinerules')) || existsSync(join(projectRoot, '.roo'));
  },

  generate(input: AdapterInput): AdapterOutput[] {
    const { content } = input;
    const lines: string[] = [];
    lines.push(`# ${content.projectName} — Cline Rules`);
    lines.push('');
    lines.push('Generated by reins. Source: .reins/constraints.yaml');
    lines.push('');
    lines.push(`Stack: ${content.projectSummary}`);
    lines.push('');

    if (content.criticalRules.length > 0) {
      lines.push('## Critical');
      lines.push('');
      lines.push(...content.criticalRules.map(r => `- ${r}`));
      lines.push('');
    }
    if (content.importantRules.length > 0) {
      lines.push('## Important');
      lines.push('');
      lines.push(...content.importantRules.map(r => `- ${r}`));
      lines.push('');
    }
    if (content.helpfulRules.length > 0) {
      lines.push('## Guidelines');
      lines.push('');
      lines.push(...content.helpfulRules.map(r => `- ${r}`));
      lines.push('');
    }
    if (content.commandsBlock) {
      lines.push('## Commands');
      lines.push('');
      lines.push(content.commandsBlock);
      lines.push('');
    }

    return [{ path: '.clinerules', content: lines.join('\n'), label: 'Cline / Roo Code rules' }];
  },
};

registerAdapter(ClineAdapter);
