import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { registerAdapter } from './base-adapter.js';
import type { AdapterDefinition, AdapterInput, AdapterOutput } from './base-adapter.js';

export const ContinueAdapter: AdapterDefinition = {
  id: 'continue',
  displayName: 'Continue.dev',
  description: '→ .continue/rules/reins.md',

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, '.continue'));
  },

  generate(input: AdapterInput): AdapterOutput[] {
    const { content } = input;
    const lines: string[] = [];
    lines.push(`# ${content.projectName} — Project Rules`);
    lines.push('');
    lines.push('Generated by reins. Source: .reins/constraints.yaml');
    lines.push('');
    const allRules = [...content.criticalRules, ...content.importantRules, ...content.helpfulRules];
    for (const rule of allRules) {
      lines.push(`- ${rule}`);
    }
    lines.push('');
    if (content.commandsBlock) {
      lines.push('## Commands');
      lines.push('');
      lines.push(content.commandsBlock);
      lines.push('');
    }

    return [{ path: '.continue/rules/reins.md', content: lines.join('\n'), label: 'Continue.dev rules' }];
  },
};

registerAdapter(ContinueAdapter);
