import type { Constraint, ConstraintsConfig } from '../constraints/schema.js';
import type { CodebaseContext } from '../scanner/types.js';
import type { Adapter } from './base-adapter.js';

export const CopilotInstructionsAdapter: Adapter = {
  name: 'copilot-instructions',
  outputPath: '.github/copilot-instructions.md',

  generate(constraints: Constraint[], context: CodebaseContext, config: ConstraintsConfig): string {
    const projectName = config.project.name;
    const stackLine = [
      ...context.stack.framework,
      ...context.stack.language,
      context.stack.packageManager,
    ]
      .filter(Boolean)
      .join(', ');

    const lines: string[] = [];
    lines.push(`# ${projectName} — GitHub Copilot Instructions`);
    lines.push('');
    lines.push(`**Stack**: ${stackLine || 'unknown'}`);
    lines.push('');
    lines.push('This file is generated by reins. Edit `.reins/constraints.yaml` to update rules.');
    lines.push('');

    const sections: Array<{ label: string; severity: 'critical' | 'important' | 'helpful' }> = [
      { label: '## Critical Rules', severity: 'critical' },
      { label: '## Important Rules', severity: 'important' },
      { label: '## Helpful Guidelines', severity: 'helpful' },
    ];

    for (const { label, severity } of sections) {
      const group = constraints.filter(c => c.severity === severity);
      lines.push(label);
      lines.push('');
      if (group.length > 0) {
        for (const c of group) {
          lines.push(`- ${c.rule}`);
        }
      } else {
        lines.push('- None');
      }
      lines.push('');
    }

    lines.push('---');
    lines.push('Full constraint definitions: `.reins/constraints.yaml`');

    return lines.join('\n') + '\n';
  },
};
