import type { Constraint, ConstraintsConfig } from '../constraints/schema.js';
import type { CodebaseContext } from '../scanner/types.js';
import type { Adapter } from './base-adapter.js';

export const CursorRulesAdapter: Adapter = {
  name: 'cursor-rules',
  outputPath: '.cursorrules',

  generate(constraints: Constraint[], context: CodebaseContext, config: ConstraintsConfig): string {
    const projectName = config.project.name;
    const lines: string[] = [];

    lines.push(`# ${projectName} Development Rules`);
    lines.push('');
    lines.push('Generated by reins. Source: .reins/constraints.yaml');
    lines.push('');

    const order: Array<'critical' | 'important' | 'helpful'> = ['critical', 'important', 'helpful'];

    for (const severity of order) {
      const group = constraints.filter(c => c.severity === severity);
      if (group.length === 0) continue;

      const label = severity.charAt(0).toUpperCase() + severity.slice(1);
      lines.push(`## ${label}`);
      lines.push('');
      for (const c of group) {
        lines.push(`- ${c.rule}`);
      }
      lines.push('');
    }

    return lines.join('\n');
  },
};
