import { existsSync } from 'node:fs';
import { join } from 'node:path';
import type { Constraint, ConstraintsConfig } from '../constraints/schema.js';
import type { CodebaseContext } from '../scanner/types.js';
import type { Adapter } from './base-adapter.js';
import { registerAdapter } from './base-adapter.js';
import type { AdapterDefinition, AdapterInput, AdapterOutput } from './base-adapter.js';

export const CursorRulesAdapter: Adapter = {
  name: 'cursor-rules',
  outputPath: '.cursorrules',

  generate(constraints: Constraint[], context: CodebaseContext, config: ConstraintsConfig): string {
    const projectName = config.project.name;
    const lines: string[] = [];

    lines.push(`# ${projectName} Development Rules`);
    lines.push('');
    lines.push('Generated by reins. Source: .reins/constraints.yaml');
    lines.push('');

    const order: Array<'critical' | 'important' | 'helpful'> = ['critical', 'important', 'helpful'];

    for (const severity of order) {
      const group = constraints.filter(c => c.severity === severity);
      if (group.length === 0) continue;

      const label = severity.charAt(0).toUpperCase() + severity.slice(1);
      lines.push(`## ${label}`);
      lines.push('');
      for (const c of group) {
        lines.push(`- ${c.rule}`);
      }
      lines.push('');
    }

    return lines.join('\n');
  },
};

export const CursorAdapter: AdapterDefinition = {
  id: 'cursor',
  displayName: 'Cursor',
  description: '→ .cursor/rules/reins.mdc',

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, '.cursor')) || existsSync(join(projectRoot, '.cursorrules'));
  },

  generate(input: AdapterInput): AdapterOutput[] {
    const { content, projectRoot } = input;
    const useNewFormat = !existsSync(join(projectRoot, '.cursorrules')) || existsSync(join(projectRoot, '.cursor', 'rules'));

    const ruleLines: string[] = [];
    for (const severity of ['critical', 'important', 'helpful'] as const) {
      const rules = severity === 'critical' ? content.criticalRules : severity === 'important' ? content.importantRules : content.helpfulRules;
      if (rules.length === 0) continue;
      const label = severity.charAt(0).toUpperCase() + severity.slice(1);
      ruleLines.push(`## ${label}`);
      ruleLines.push('');
      ruleLines.push(...rules.map(r => `- ${r}`));
      ruleLines.push('');
    }

    const body = `# ${content.projectName} Development Rules\n\nGenerated by reins. Source: .reins/constraints.yaml\n\n${ruleLines.join('\n')}`;

    if (useNewFormat) {
      const mdc = `---\ndescription: Project constraints generated by reins\nglobs: \"**\"\nalwaysApply: true\n---\n\n${body}`;
      return [{ path: '.cursor/rules/reins.mdc', content: mdc, label: 'Cursor rules (new format)' }];
    }
    return [{ path: '.cursorrules', content: body, label: 'Cursor rules' }];
  },
};

registerAdapter(CursorAdapter);
