import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { registerAdapter } from './base-adapter.js';
import type { AdapterDefinition, AdapterInput, AdapterOutput } from './base-adapter.js';

export const GeminiAdapter: AdapterDefinition = {
  id: 'gemini',
  displayName: 'Gemini CLI',
  description: '→ GEMINI.md',

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, 'GEMINI.md'));
  },

  generate(input: AdapterInput): AdapterOutput[] {
    const { content } = input;
    const lines: string[] = [];
    lines.push(`# ${content.projectName}`);
    lines.push('');
    lines.push('Generated by reins. Source: .reins/constraints.yaml');
    lines.push('');
    lines.push(`**Stack**: ${content.projectSummary}`);
    lines.push('');
    if (content.commandsBlock) {
      lines.push('## Commands');
      lines.push('');
      lines.push(content.commandsBlock);
      lines.push('');
    }
    lines.push('## Rules');
    lines.push('');
    const allRules = [...content.criticalRules, ...content.importantRules];
    for (const rule of allRules) {
      lines.push(`- ${rule}`);
    }
    lines.push('');

    return [{ path: 'GEMINI.md', content: lines.join('\n'), label: 'Gemini CLI context' }];
  },
};

registerAdapter(GeminiAdapter);
