import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { registerAdapter } from './base-adapter.js';
import type { AdapterDefinition, AdapterInput, AdapterOutput } from './base-adapter.js';

export const OpenCodeAdapter: AdapterDefinition = {
  id: 'opencode',
  displayName: 'OpenCode',
  description: '→ AGENTS.md (root)',

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, 'opencode.json'))
      || existsSync(join(projectRoot, 'opencode.jsonc'))
      || existsSync(join(projectRoot, '.opencode'));
  },

  generate(input: AdapterInput): AdapterOutput[] {
    const { content } = input;
    const lines: string[] = [];
    lines.push(`# ${content.projectName}`);
    lines.push('');
    lines.push('Generated by reins. Source: .reins/constraints.yaml');
    lines.push('');
    lines.push(`**Stack**: ${content.projectSummary}`);
    lines.push(`**Architecture**: ${content.architectureSummary}`);
    lines.push('');

    if (content.commandsBlock) {
      lines.push('## Commands');
      lines.push('');
      lines.push(content.commandsBlock);
      lines.push('');
    }

    if (content.criticalRules.length > 0) {
      lines.push('## Critical');
      lines.push('');
      lines.push(...content.criticalRules.map(r => `- ${r}`));
      lines.push('');
    }
    if (content.importantRules.length > 0) {
      lines.push('## Important');
      lines.push('');
      lines.push(...content.importantRules.map(r => `- ${r}`));
      lines.push('');
    }
    if (content.helpfulRules.length > 0) {
      lines.push('## Guidelines');
      lines.push('');
      lines.push(...content.helpfulRules.map(r => `- ${r}`));
      lines.push('');
    }

    if (content.conventionsBlock) {
      lines.push('## Conventions');
      lines.push('');
      lines.push(content.conventionsBlock);
      lines.push('');
    }

    return [{ path: 'AGENTS.md', content: lines.join('\n'), label: 'OpenCode instructions' }];
  },
};

registerAdapter(OpenCodeAdapter);
