import type { Constraint, ConstraintsConfig } from '../constraints/schema.js';
import type { CodebaseContext } from '../scanner/types.js';
import type { Adapter } from './base-adapter.js';

export const WindsurfRulesAdapter: Adapter = {
  name: 'windsurf-rules',
  outputPath: '.windsurfrules',

  generate(constraints: Constraint[], context: CodebaseContext, config: ConstraintsConfig): string {
    const lines: string[] = [];
    lines.push('# Windsurf Rules — generated by reins');
    lines.push(`# Project: ${config.project.name}`);
    lines.push('');

    const order: Array<'critical' | 'important' | 'helpful'> = ['critical', 'important', 'helpful'];

    for (const severity of order) {
      const group = constraints.filter(c => c.severity === severity);
      for (const c of group) {
        const tag =
          severity === 'critical'
            ? '[REQUIRED]'
            : severity === 'important'
              ? '[IMPORTANT]'
              : '[GUIDELINE]';
        lines.push(`${tag} ${c.rule}`);
      }
    }

    lines.push('');
    return lines.join('\n');
  },
};
