import { existsSync } from 'node:fs';
import { join } from 'node:path';
import type { Constraint, ConstraintsConfig } from '../constraints/schema.js';
import type { CodebaseContext } from '../scanner/types.js';
import type { Adapter } from './base-adapter.js';
import { registerAdapter } from './base-adapter.js';
import type { AdapterDefinition, AdapterInput, AdapterOutput } from './base-adapter.js';

export const WindsurfRulesAdapter: Adapter = {
  name: 'windsurf-rules',
  outputPath: '.windsurfrules',

  generate(constraints: Constraint[], context: CodebaseContext, config: ConstraintsConfig): string {
    const lines: string[] = [];
    lines.push('# Windsurf Rules — generated by reins');
    lines.push(`# Project: ${config.project.name}`);
    lines.push('');

    const order: Array<'critical' | 'important' | 'helpful'> = ['critical', 'important', 'helpful'];

    for (const severity of order) {
      const group = constraints.filter(c => c.severity === severity);
      for (const c of group) {
        const tag =
          severity === 'critical'
            ? '[REQUIRED]'
            : severity === 'important'
              ? '[IMPORTANT]'
              : '[GUIDELINE]';
        lines.push(`${tag} ${c.rule}`);
      }
    }

    lines.push('');
    return lines.join('\n');
  },
};

export const WindsurfAdapter: AdapterDefinition = {
  id: 'windsurf',
  displayName: 'Windsurf',
  description: '→ .windsurf/rules/reins.md',

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, '.windsurf')) || existsSync(join(projectRoot, '.windsurfrules'));
  },

  generate(input: AdapterInput): AdapterOutput[] {
    const { content, projectRoot } = input;
    const useNewFormat = !existsSync(join(projectRoot, '.windsurfrules')) || existsSync(join(projectRoot, '.windsurf', 'rules'));

    const lines: string[] = [];
    lines.push(`# Windsurf Rules — ${content.projectName}`);
    lines.push('');
    lines.push('Generated by reins. Source: .reins/constraints.yaml');
    lines.push('');
    for (const [severity, rules] of [['critical', content.criticalRules], ['important', content.importantRules], ['helpful', content.helpfulRules]] as const) {
      const tag = severity === 'critical' ? '[REQUIRED]' : severity === 'important' ? '[IMPORTANT]' : '[GUIDELINE]';
      for (const rule of rules) {
        lines.push(`${tag} ${rule}`);
      }
    }
    lines.push('');

    const body = lines.join('\n');
    const path = useNewFormat ? '.windsurf/rules/reins.md' : '.windsurfrules';
    return [{ path, content: body, label: 'Windsurf rules' }];
  },
};

registerAdapter(WindsurfAdapter);
