import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import type { CodebaseContext } from '../scanner/types.js';
import type { Constraint } from '../constraints/schema.js';

// ---------------------------------------------------------------------------
// Topic grouping
// ---------------------------------------------------------------------------

const TOPIC_RULES: Array<{ pattern: RegExp; topic: string }> = [
  { pattern: /api|route|endpoint/i, topic: 'api-patterns' },
  { pattern: /test|coverage|fixture/i, topic: 'testing-patterns' },
  { pattern: /error|exception|throw/i, topic: 'error-handling' },
  { pattern: /import|module|depend/i, topic: 'module-patterns' },
];

export function groupConstraintsByTopic(constraints: Constraint[]): Map<string, Constraint[]> {
  const groups = new Map<string, Constraint[]>();

  for (const c of constraints) {
    let assigned = false;
    for (const { pattern, topic } of TOPIC_RULES) {
      if (pattern.test(c.rule)) {
        if (!groups.has(topic)) groups.set(topic, []);
        groups.get(topic)!.push(c);
        assigned = true;
        break;
      }
    }
    if (!assigned) {
      if (!groups.has('general-patterns')) groups.set('general-patterns', []);
      groups.get('general-patterns')!.push(c);
    }
  }

  return groups;
}

// ---------------------------------------------------------------------------
// Render a single pattern file
// ---------------------------------------------------------------------------

function renderPatternFile(topic: string, constraints: Constraint[], context: CodebaseContext): string {
  const title = topic
    .split('-')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');

  const lines: string[] = [];
  lines.push(`# ${title}`);
  lines.push('');
  lines.push(`> Generated by reins for ${context.stack.language.join(', ') || 'this project'}.`);
  lines.push('');

  for (const c of constraints) {
    lines.push(`## ${c.id}`);
    lines.push('');
    lines.push(`**Rule**: ${c.rule}`);
    lines.push('');
    lines.push(`**Severity**: ${c.severity}`);
    lines.push('');
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

export function generateL2(
  projectRoot: string,
  constraints: Constraint[],
  context: CodebaseContext,
): void {
  const helpful = constraints.filter(c => c.severity === 'helpful');
  if (helpful.length === 0) return;

  const patternsDir = join(projectRoot, '.reins', 'patterns');
  mkdirSync(patternsDir, { recursive: true });

  const groups = groupConstraintsByTopic(helpful);

  for (const [topic, topicConstraints] of groups) {
    const content = renderPatternFile(topic, topicConstraints, context);
    writeFileSync(join(patternsDir, `${topic}.md`), content, 'utf-8');
  }
}
